### ISSUE TITLE
Fix command handler not waiting for response before printing new line

### ISSUE THREAD

**Issue by zNotChill** [zNotChill/terminal#1]
please help Idk how to fix this

See [this](https://github.com/zNotChill/terminal/blob/957e3e60ea8002d7aaa6e16c1a8eeb7f49b57795/app/src/terminal.js#L53) and [this
](https://github.com/zNotChill/terminal/blob/957e3e60ea8002d7aaa6e16c1a8eeb7f49b57795/app/src/commands.js#L15C11-L15C11).

**Comment by blockarchitech** [comment]
https://github.com/zNotChill/terminal/blob/957e3e60ea8002d7aaa6e16c1a8eeb7f49b57795/app/src/commands.js#L23C7-L23C7

Are you not checking if the callback is async or not? That might be your issue if synchronous vs asynchronous callback funcs

**Comment by zNotChill** [comment]
What would this change @blockarchitech?
I am terrible at async vs sync but I know how to implement this but what would it change?
```this.callback.constructor.name === "AsyncFunction"```

**Comment by blockarchitech** [comment]
The callback has to be asynchronous or the newline function falls apart

**Comment by zNotChill** [comment]
wait but how

I was just checking for if there was a response from the execute function and if there is then put the new line

**Comment by zNotChill** [comment]
I can finally say with a ton of confidence that I fixed this

..after a dozen code rewrites
